apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-leplus-co-tls
spec:
  secretName: k8s-leplus-co-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: k8s.leplus.co
  dnsNames:
    - k8s.leplus.co
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.leplus.co
